// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// The casting technology/provider type.
///
/// This enum allows the Flutter layer to understand which technology is being
/// used, while keeping the API unified. The native layer handles the specifics.
enum CastingProvider {
  /// Google Cast (Chromecast, Android TV, Nest devices)
  /// Available on: Android, iOS
  chromecast,
  /// Apple AirPlay (Apple TV, AirPlay 2 speakers, AirPlay-enabled TVs)
  /// Available on: iOS only
  airplay,
}

/// The current state of the casting connection.
///
/// Modeled after session states from Google Cast SDK.
enum CastingConnectionState {
  /// No casting session, not connected to any device
  disconnected,
  /// Attempting to connect to a cast device
  connecting,
  /// Connected to a cast device, ready to load media
  connected,
}

/// The current playback state on the remote device.
enum CastingPlaybackState {
  /// No media loaded
  idle,
  /// Media is loading/buffering
  loading,
  /// Media is playing
  playing,
  /// Media is paused
  paused,
  /// Playback has ended
  ended,
  /// An error occurred during playback
  error,
}

/// Media content type for proper receiver handling.
enum MediaType {
  /// Video content (movies, TV shows, video clips)
  video,
  /// Audio content (music, podcasts, audiobooks)
  audio,
}

/// Represents a discovered cast-capable device.
///
/// This is a unified representation that works for both Chromecast and AirPlay
/// devices. The [provider] field indicates which technology is being used.
class CastDevice {
  CastDevice({
    required this.id,
    required this.name,
    required this.provider,
    this.modelName,
  });

  /// Unique identifier for the device.
  /// - Chromecast: Route ID from MediaRouter
  /// - AirPlay: UID from AVRouteDetector
  String id;

  /// Human-readable device name (e.g., "Living Room TV")
  String name;

  /// The casting technology this device uses
  CastingProvider provider;

  /// Device model name if available (e.g., "Chromecast Ultra", "Apple TV 4K")
  String? modelName;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      provider,
      modelName,
    ];
  }

  Object encode() {
    return _toList();  }

  static CastDevice decode(Object result) {
    result as List<Object?>;
    return CastDevice(
      id: result[0]! as String,
      name: result[1]! as String,
      provider: result[2]! as CastingProvider,
      modelName: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CastDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Information about the media to be cast.
///
/// Modeled after MediaInfo from Google Cast SDK.
/// @see https://developers.google.com/cast/docs/reference/android/com/google/android/gms/cast/MediaInfo
class MediaInfo {
  MediaInfo({
    required this.contentUrl,
    required this.title,
    required this.mediaType,
    this.subtitle,
    this.imageUrl,
    this.contentType,
    this.duration,
  });

  /// URL of the media content.
  /// Must be accessible by the receiver device (not localhost).
  String contentUrl;

  /// Title displayed on the receiver (e.g., "Big Buck Bunny")
  String title;

  /// Type of media content
  MediaType mediaType;

  /// Subtitle/artist displayed on the receiver
  String? subtitle;

  /// URL of the thumbnail/poster image
  String? imageUrl;

  /// MIME type of the content (e.g., "video/mp4", "audio/mpeg")
  /// If not provided, the receiver will try to detect it.
  String? contentType;

  /// Duration in milliseconds (optional, receiver can detect)
  int? duration;

  List<Object?> _toList() {
    return <Object?>[
      contentUrl,
      title,
      mediaType,
      subtitle,
      imageUrl,
      contentType,
      duration,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaInfo decode(Object result) {
    result as List<Object?>;
    return MediaInfo(
      contentUrl: result[0]! as String,
      title: result[1]! as String,
      mediaType: result[2]! as MediaType,
      subtitle: result[3] as String?,
      imageUrl: result[4] as String?,
      contentType: result[5] as String?,
      duration: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Current state of the casting session and playback.
///
/// Sent from native to Flutter via CastingFlutterApi.onStateChanged
class CastingState {
  CastingState({
    required this.connectionState,
    required this.playbackState,
    this.connectedDevice,
    this.currentMedia,
    this.positionMs,
    this.durationMs,
    this.errorMessage,
  });

  /// Current connection state
  CastingConnectionState connectionState;

  /// Current playback state
  CastingPlaybackState playbackState;

  /// Currently connected device (null if disconnected)
  CastDevice? connectedDevice;

  /// Currently loaded media (null if no media loaded)
  MediaInfo? currentMedia;

  /// Current playback position in milliseconds
  int? positionMs;

  /// Total duration in milliseconds
  int? durationMs;

  /// Error message if playbackState is error
  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      connectionState,
      playbackState,
      connectedDevice,
      currentMedia,
      positionMs,
      durationMs,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static CastingState decode(Object result) {
    result as List<Object?>;
    return CastingState(
      connectionState: result[0]! as CastingConnectionState,
      playbackState: result[1]! as CastingPlaybackState,
      connectedDevice: result[2] as CastDevice?,
      currentMedia: result[3] as MediaInfo?,
      positionMs: result[4] as int?,
      durationMs: result[5] as int?,
      errorMessage: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CastingState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CastingProvider) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is CastingConnectionState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is CastingPlaybackState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is MediaType) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is CastDevice) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is MediaInfo) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is CastingState) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CastingProvider.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CastingConnectionState.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CastingPlaybackState.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : MediaType.values[value];
      case 133: 
        return CastDevice.decode(readValue(buffer)!);
      case 134: 
        return MediaInfo.decode(readValue(buffer)!);
      case 135: 
        return CastingState.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// API for Flutter to call native platform code.
///
/// This is the main interface for controlling casting from Dart.
/// Implementations exist for:
/// - Android: Chromecast via Cast SDK + MediaRouter
/// - iOS: Chromecast via Cast SDK + AirPlay via AVFoundation
class CastingHostApi {
  /// Constructor for [CastingHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CastingHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Start discovering all available cast devices.
  ///
  /// On Android: Discovers Chromecast devices via MediaRouter.
  /// On iOS: Discovers Chromecast (GCKDiscoveryManager) + AirPlay (AVRouteDetector).
  ///
  /// Results are delivered via [CastingFlutterApi.onDevicesChanged].
  Future<void> startDiscovery() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.startDiscovery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Stop all device discovery.
  Future<void> stopDiscovery() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.stopDiscovery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get all currently discovered devices.
  Future<List<CastDevice>> getDiscoveredDevices() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.getDiscoveredDevices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<CastDevice>();
    }
  }

  /// Connect to a specific Chromecast device.
  ///
  /// ⚠️ IMPORTANT: This method only works for Chromecast devices!
  ///
  /// For AirPlay devices, use [showAirPlayPicker] instead - Apple requires
  /// user interaction via their system UI (AVRoutePickerView).
  ///
  /// @param deviceId The unique ID of the Chromecast device to connect to.
  ///
  /// Connection state changes are delivered via CastingFlutterApi.onStateChanged.
  Future<void> connect(String deviceId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[deviceId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Disconnect from the current cast device.
  ///
  /// This will stop any playing media and end the casting session.
  /// Works for both Chromecast and AirPlay.
  Future<void> disconnect() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Show the native AirPlay device picker (iOS only).
  ///
  /// This presents a system UI (AVRoutePickerView) where the user can select
  /// an AirPlay device. Apple does not allow programmatic device selection.
  ///
  /// On Android: This is a no-op (AirPlay not available).
  ///
  /// After the user selects a device, the connection state will be updated
  /// via CastingFlutterApi.onStateChanged.
  Future<void> showAirPlayPicker() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.showAirPlayPicker$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Load and start playing media on the connected device.
  ///
  /// @param mediaInfo Information about the media to play.
  /// @param autoplay Whether to start playing immediately (default: true).
  /// @param positionMs Starting position in milliseconds (default: 0).
  ///
  /// For Chromecast: Uses RemoteMediaClient.load()
  /// For AirPlay: Configures AVPlayer with the URL
  Future<void> loadMedia(MediaInfo mediaInfo, bool autoplay, int positionMs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.loadMedia$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[mediaInfo, autoplay, positionMs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Resume playback of paused media.
  Future<void> play() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.play$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Pause playback.
  Future<void> pause() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.pause$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Seek to a specific position.
  ///
  /// @param positionMs Target position in milliseconds.
  Future<void> seek(int positionMs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.seek$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[positionMs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Stop playback and unload media.
  ///
  /// This does NOT disconnect from the device.
  Future<void> stop() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.stop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set the playback volume on the receiver.
  ///
  /// @param volume Volume level from 0.0 to 1.0.
  Future<void> setVolume(double volume) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.setVolume$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[volume]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set mute state on the receiver.
  Future<void> setMuted(bool muted) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pitcher.CastingHostApi.setMuted$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[muted]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// API for native platform code to call Flutter.
///
/// This enables the native layer to push updates to the Dart layer,
/// following an event-driven architecture pattern.
abstract class CastingFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Called when the list of discovered devices changes.
  ///
  /// This is triggered when:
  /// - A new device is discovered
  /// - A device disappears (goes offline)
  /// - Device properties change
  void onDevicesChanged(List<CastDevice> devices);

  /// Called when the casting state changes.
  ///
  /// This includes:
  /// - Connection state changes (connecting, connected, disconnected)
  /// - Playback state changes (loading, playing, paused, ended)
  /// - Position updates during playback
  /// - Error events
  void onStateChanged(CastingState state);

  static void setUp(CastingFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pitcher.CastingFlutterApi.onDevicesChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pitcher.CastingFlutterApi.onDevicesChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<CastDevice>? arg_devices = (args[0] as List<Object?>?)?.cast<CastDevice>();
          assert(arg_devices != null,
              'Argument for dev.flutter.pigeon.pitcher.CastingFlutterApi.onDevicesChanged was null, expected non-null List<CastDevice>.');
          try {
            api.onDevicesChanged(arg_devices!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pitcher.CastingFlutterApi.onStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pitcher.CastingFlutterApi.onStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CastingState? arg_state = (args[0] as CastingState?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.pitcher.CastingFlutterApi.onStateChanged was null, expected non-null CastingState.');
          try {
            api.onStateChanged(arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
