// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class CastingApiError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "CastingApiError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? CastingApiError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> CastingApiError {
  return CastingApiError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsCastingApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsCastingApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsCastingApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashCastingApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashCastingApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashCastingApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// The casting technology/provider type.
///
/// This enum allows the Flutter layer to understand which technology is being
/// used, while keeping the API unified. The native layer handles the specifics.
enum CastingProvider: Int {
  /// Google Cast (Chromecast, Android TV, Nest devices)
  /// Available on: Android, iOS
  case chromecast = 0
  /// Apple AirPlay (Apple TV, AirPlay 2 speakers, AirPlay-enabled TVs)
  /// Available on: iOS only
  case airplay = 1
}

/// The current state of the casting connection.
///
/// Modeled after session states from Google Cast SDK.
enum CastingConnectionState: Int {
  /// No casting session, not connected to any device
  case disconnected = 0
  /// Attempting to connect to a cast device
  case connecting = 1
  /// Connected to a cast device, ready to load media
  case connected = 2
}

/// The current playback state on the remote device.
enum CastingPlaybackState: Int {
  /// No media loaded
  case idle = 0
  /// Media is loading/buffering
  case loading = 1
  /// Media is playing
  case playing = 2
  /// Media is paused
  case paused = 3
  /// Playback has ended
  case ended = 4
  /// An error occurred during playback
  case error = 5
}

/// Media content type for proper receiver handling.
enum MediaType: Int {
  /// Video content (movies, TV shows, video clips)
  case video = 0
  /// Audio content (music, podcasts, audiobooks)
  case audio = 1
}

/// Represents a discovered cast-capable device.
///
/// This is a unified representation that works for both Chromecast and AirPlay
/// devices. The [provider] field indicates which technology is being used.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CastDevice: Hashable {
  /// Unique identifier for the device.
  /// - Chromecast: Route ID from MediaRouter
  /// - AirPlay: UID from AVRouteDetector
  var id: String
  /// Human-readable device name (e.g., "Living Room TV")
  var name: String
  /// The casting technology this device uses
  var provider: CastingProvider
  /// Device model name if available (e.g., "Chromecast Ultra", "Apple TV 4K")
  var modelName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastDevice? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let provider = pigeonVar_list[2] as! CastingProvider
    let modelName: String? = nilOrValue(pigeonVar_list[3])

    return CastDevice(
      id: id,
      name: name,
      provider: provider,
      modelName: modelName
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      provider,
      modelName,
    ]
  }
  static func == (lhs: CastDevice, rhs: CastDevice) -> Bool {
    return deepEqualsCastingApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastingApi(value: toList(), hasher: &hasher)
  }
}

/// Information about the media to be cast.
///
/// Modeled after MediaInfo from Google Cast SDK.
/// @see https://developers.google.com/cast/docs/reference/android/com/google/android/gms/cast/MediaInfo
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfo: Hashable {
  /// URL of the media content.
  /// Must be accessible by the receiver device (not localhost).
  var contentUrl: String
  /// Title displayed on the receiver (e.g., "Big Buck Bunny")
  var title: String
  /// Type of media content
  var mediaType: MediaType
  /// Subtitle/artist displayed on the receiver
  var subtitle: String? = nil
  /// URL of the thumbnail/poster image
  var imageUrl: String? = nil
  /// MIME type of the content (e.g., "video/mp4", "audio/mpeg")
  /// If not provided, the receiver will try to detect it.
  var contentType: String? = nil
  /// Duration in milliseconds (optional, receiver can detect)
  var duration: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfo? {
    let contentUrl = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let mediaType = pigeonVar_list[2] as! MediaType
    let subtitle: String? = nilOrValue(pigeonVar_list[3])
    let imageUrl: String? = nilOrValue(pigeonVar_list[4])
    let contentType: String? = nilOrValue(pigeonVar_list[5])
    let duration: Int64? = nilOrValue(pigeonVar_list[6])

    return MediaInfo(
      contentUrl: contentUrl,
      title: title,
      mediaType: mediaType,
      subtitle: subtitle,
      imageUrl: imageUrl,
      contentType: contentType,
      duration: duration
    )
  }
  func toList() -> [Any?] {
    return [
      contentUrl,
      title,
      mediaType,
      subtitle,
      imageUrl,
      contentType,
      duration,
    ]
  }
  static func == (lhs: MediaInfo, rhs: MediaInfo) -> Bool {
    return deepEqualsCastingApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastingApi(value: toList(), hasher: &hasher)
  }
}

/// Current state of the casting session and playback.
///
/// Sent from native to Flutter via CastingFlutterApi.onStateChanged
///
/// Generated class from Pigeon that represents data sent in messages.
struct CastingState: Hashable {
  /// Current connection state
  var connectionState: CastingConnectionState
  /// Current playback state
  var playbackState: CastingPlaybackState
  /// Currently connected device (null if disconnected)
  var connectedDevice: CastDevice? = nil
  /// Currently loaded media (null if no media loaded)
  var currentMedia: MediaInfo? = nil
  /// Current playback position in milliseconds
  var positionMs: Int64? = nil
  /// Total duration in milliseconds
  var durationMs: Int64? = nil
  /// Error message if playbackState is error
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastingState? {
    let connectionState = pigeonVar_list[0] as! CastingConnectionState
    let playbackState = pigeonVar_list[1] as! CastingPlaybackState
    let connectedDevice: CastDevice? = nilOrValue(pigeonVar_list[2])
    let currentMedia: MediaInfo? = nilOrValue(pigeonVar_list[3])
    let positionMs: Int64? = nilOrValue(pigeonVar_list[4])
    let durationMs: Int64? = nilOrValue(pigeonVar_list[5])
    let errorMessage: String? = nilOrValue(pigeonVar_list[6])

    return CastingState(
      connectionState: connectionState,
      playbackState: playbackState,
      connectedDevice: connectedDevice,
      currentMedia: currentMedia,
      positionMs: positionMs,
      durationMs: durationMs,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      connectionState,
      playbackState,
      connectedDevice,
      currentMedia,
      positionMs,
      durationMs,
      errorMessage,
    ]
  }
  static func == (lhs: CastingState, rhs: CastingState) -> Bool {
    return deepEqualsCastingApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastingApi(value: toList(), hasher: &hasher)
  }
}

private class CastingApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CastingProvider(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CastingConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CastingPlaybackState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MediaType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return CastDevice.fromList(self.readValue() as! [Any?])
    case 134:
      return MediaInfo.fromList(self.readValue() as! [Any?])
    case 135:
      return CastingState.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CastingApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CastingProvider {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CastingConnectionState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CastingPlaybackState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? MediaType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? CastDevice {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? MediaInfo {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? CastingState {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CastingApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CastingApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CastingApiPigeonCodecWriter(data: data)
  }
}

class CastingApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CastingApiPigeonCodec(readerWriter: CastingApiPigeonCodecReaderWriter())
}

/// API for Flutter to call native platform code.
///
/// This is the main interface for controlling casting from Dart.
/// Implementations exist for:
/// - Android: Chromecast via Cast SDK + MediaRouter
/// - iOS: Chromecast via Cast SDK + AirPlay via AVFoundation
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CastingHostApi {
  /// Start discovering all available cast devices.
  ///
  /// On Android: Discovers Chromecast devices via MediaRouter.
  /// On iOS: Discovers Chromecast (GCKDiscoveryManager) + AirPlay (AVRouteDetector).
  ///
  /// Results are delivered via [CastingFlutterApi.onDevicesChanged].
  func startDiscovery() throws
  /// Stop all device discovery.
  func stopDiscovery() throws
  /// Get all currently discovered devices.
  func getDiscoveredDevices() throws -> [CastDevice]
  /// Connect to a specific Chromecast device.
  ///
  /// ⚠️ IMPORTANT: This method only works for Chromecast devices!
  ///
  /// For AirPlay devices, use [showAirPlayPicker] instead - Apple requires
  /// user interaction via their system UI (AVRoutePickerView).
  ///
  /// @param deviceId The unique ID of the Chromecast device to connect to.
  ///
  /// Connection state changes are delivered via CastingFlutterApi.onStateChanged.
  func connect(deviceId: String) throws
  /// Disconnect from the current cast device.
  ///
  /// This will stop any playing media and end the casting session.
  /// Works for both Chromecast and AirPlay.
  func disconnect() throws
  /// Show the native AirPlay device picker (iOS only).
  ///
  /// This presents a system UI (AVRoutePickerView) where the user can select
  /// an AirPlay device. Apple does not allow programmatic device selection.
  ///
  /// On Android: This is a no-op (AirPlay not available).
  ///
  /// After the user selects a device, the connection state will be updated
  /// via CastingFlutterApi.onStateChanged.
  func showAirPlayPicker() throws
  /// Load and start playing media on the connected device.
  ///
  /// @param mediaInfo Information about the media to play.
  /// @param autoplay Whether to start playing immediately (default: true).
  /// @param positionMs Starting position in milliseconds (default: 0).
  ///
  /// For Chromecast: Uses RemoteMediaClient.load()
  /// For AirPlay: Configures AVPlayer with the URL
  func loadMedia(mediaInfo: MediaInfo, autoplay: Bool, positionMs: Int64) throws
  /// Resume playback of paused media.
  func play() throws
  /// Pause playback.
  func pause() throws
  /// Seek to a specific position.
  ///
  /// @param positionMs Target position in milliseconds.
  func seek(positionMs: Int64) throws
  /// Stop playback and unload media.
  ///
  /// This does NOT disconnect from the device.
  func stop() throws
  /// Set the playback volume on the receiver.
  ///
  /// @param volume Volume level from 0.0 to 1.0.
  func setVolume(volume: Double) throws
  /// Set mute state on the receiver.
  func setMuted(muted: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CastingHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CastingApiPigeonCodec.shared }
  /// Sets up an instance of `CastingHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CastingHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Start discovering all available cast devices.
    ///
    /// On Android: Discovers Chromecast devices via MediaRouter.
    /// On iOS: Discovers Chromecast (GCKDiscoveryManager) + AirPlay (AVRouteDetector).
    ///
    /// Results are delivered via [CastingFlutterApi.onDevicesChanged].
    let startDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.startDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.startDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDiscoveryChannel.setMessageHandler(nil)
    }
    /// Stop all device discovery.
    let stopDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.stopDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.stopDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDiscoveryChannel.setMessageHandler(nil)
    }
    /// Get all currently discovered devices.
    let getDiscoveredDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.getDiscoveredDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDiscoveredDevicesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDiscoveredDevices()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDiscoveredDevicesChannel.setMessageHandler(nil)
    }
    /// Connect to a specific Chromecast device.
    ///
    /// ⚠️ IMPORTANT: This method only works for Chromecast devices!
    ///
    /// For AirPlay devices, use [showAirPlayPicker] instead - Apple requires
    /// user interaction via their system UI (AVRoutePickerView).
    ///
    /// @param deviceId The unique ID of the Chromecast device to connect to.
    ///
    /// Connection state changes are delivered via CastingFlutterApi.onStateChanged.
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        do {
          try api.connect(deviceId: deviceIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    /// Disconnect from the current cast device.
    ///
    /// This will stop any playing media and end the casting session.
    /// Works for both Chromecast and AirPlay.
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        do {
          try api.disconnect()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    /// Show the native AirPlay device picker (iOS only).
    ///
    /// This presents a system UI (AVRoutePickerView) where the user can select
    /// an AirPlay device. Apple does not allow programmatic device selection.
    ///
    /// On Android: This is a no-op (AirPlay not available).
    ///
    /// After the user selects a device, the connection state will be updated
    /// via CastingFlutterApi.onStateChanged.
    let showAirPlayPickerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.showAirPlayPicker\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showAirPlayPickerChannel.setMessageHandler { _, reply in
        do {
          try api.showAirPlayPicker()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showAirPlayPickerChannel.setMessageHandler(nil)
    }
    /// Load and start playing media on the connected device.
    ///
    /// @param mediaInfo Information about the media to play.
    /// @param autoplay Whether to start playing immediately (default: true).
    /// @param positionMs Starting position in milliseconds (default: 0).
    ///
    /// For Chromecast: Uses RemoteMediaClient.load()
    /// For AirPlay: Configures AVPlayer with the URL
    let loadMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.loadMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaInfoArg = args[0] as! MediaInfo
        let autoplayArg = args[1] as! Bool
        let positionMsArg = args[2] as! Int64
        do {
          try api.loadMedia(mediaInfo: mediaInfoArg, autoplay: autoplayArg, positionMs: positionMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadMediaChannel.setMessageHandler(nil)
    }
    /// Resume playback of paused media.
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { _, reply in
        do {
          try api.play()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    /// Pause playback.
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    /// Seek to a specific position.
    ///
    /// @param positionMs Target position in milliseconds.
    let seekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.seek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionMsArg = args[0] as! Int64
        do {
          try api.seek(positionMs: positionMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekChannel.setMessageHandler(nil)
    }
    /// Stop playback and unload media.
    ///
    /// This does NOT disconnect from the device.
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Set the playback volume on the receiver.
    ///
    /// @param volume Volume level from 0.0 to 1.0.
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let volumeArg = args[0] as! Double
        do {
          try api.setVolume(volume: volumeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
    /// Set mute state on the receiver.
    let setMutedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastingHostApi.setMuted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMutedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mutedArg = args[0] as! Bool
        do {
          try api.setMuted(muted: mutedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMutedChannel.setMessageHandler(nil)
    }
  }
}
/// API for native platform code to call Flutter.
///
/// This enables the native layer to push updates to the Dart layer,
/// following an event-driven architecture pattern.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CastingFlutterApiProtocol {
  /// Called when the list of discovered devices changes.
  ///
  /// This is triggered when:
  /// - A new device is discovered
  /// - A device disappears (goes offline)
  /// - Device properties change
  func onDevicesChanged(devices devicesArg: [CastDevice], completion: @escaping (Result<Void, CastingApiError>) -> Void)
  /// Called when the casting state changes.
  ///
  /// This includes:
  /// - Connection state changes (connecting, connected, disconnected)
  /// - Playback state changes (loading, playing, paused, ended)
  /// - Position updates during playback
  /// - Error events
  func onStateChanged(state stateArg: CastingState, completion: @escaping (Result<Void, CastingApiError>) -> Void)
}
class CastingFlutterApi: CastingFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CastingApiPigeonCodec {
    return CastingApiPigeonCodec.shared
  }
  /// Called when the list of discovered devices changes.
  ///
  /// This is triggered when:
  /// - A new device is discovered
  /// - A device disappears (goes offline)
  /// - Device properties change
  func onDevicesChanged(devices devicesArg: [CastDevice], completion: @escaping (Result<Void, CastingApiError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pitcher.CastingFlutterApi.onDevicesChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([devicesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(CastingApiError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when the casting state changes.
  ///
  /// This includes:
  /// - Connection state changes (connecting, connected, disconnected)
  /// - Playback state changes (loading, playing, paused, ended)
  /// - Position updates during playback
  /// - Error events
  func onStateChanged(state stateArg: CastingState, completion: @escaping (Result<Void, CastingApiError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pitcher.CastingFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(CastingApiError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
