// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class CastApiError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "CastApiError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? CastApiError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> CastApiError {
  return CastApiError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsCastApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsCastApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsCastApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashCastApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashCastApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashCastApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum CastProvider: Int {
  case chromecast = 0
  case airplay = 1
}

enum CastConnectionState: Int {
  case disconnected = 0
  case connecting = 1
  case connected = 2
}

enum CastPlaybackState: Int {
  case idle = 0
  case loading = 1
  case playing = 2
  case paused = 3
  case ended = 4
  case error = 5
}

enum MediaType: Int {
  case video = 0
  case audio = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct CastDevice: Hashable {
  var id: String
  var name: String
  var provider: CastProvider
  var modelName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastDevice? {
    let id = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let provider = pigeonVar_list[2] as! CastProvider
    let modelName: String? = nilOrValue(pigeonVar_list[3])

    return CastDevice(
      id: id,
      name: name,
      provider: provider,
      modelName: modelName
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      provider,
      modelName,
    ]
  }
  static func == (lhs: CastDevice, rhs: CastDevice) -> Bool {
    return deepEqualsCastApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfo: Hashable {
  var contentUrl: String
  var title: String
  var mediaType: MediaType
  var subtitle: String? = nil
  var imageUrl: String? = nil
  var contentType: String? = nil
  var duration: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfo? {
    let contentUrl = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let mediaType = pigeonVar_list[2] as! MediaType
    let subtitle: String? = nilOrValue(pigeonVar_list[3])
    let imageUrl: String? = nilOrValue(pigeonVar_list[4])
    let contentType: String? = nilOrValue(pigeonVar_list[5])
    let duration: Int64? = nilOrValue(pigeonVar_list[6])

    return MediaInfo(
      contentUrl: contentUrl,
      title: title,
      mediaType: mediaType,
      subtitle: subtitle,
      imageUrl: imageUrl,
      contentType: contentType,
      duration: duration
    )
  }
  func toList() -> [Any?] {
    return [
      contentUrl,
      title,
      mediaType,
      subtitle,
      imageUrl,
      contentType,
      duration,
    ]
  }
  static func == (lhs: MediaInfo, rhs: MediaInfo) -> Bool {
    return deepEqualsCastApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CastSessionState: Hashable {
  var connectionState: CastConnectionState
  var playbackState: CastPlaybackState
  var connectedDevice: CastDevice? = nil
  var currentMedia: MediaInfo? = nil
  var positionMs: Int64? = nil
  var durationMs: Int64? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CastSessionState? {
    let connectionState = pigeonVar_list[0] as! CastConnectionState
    let playbackState = pigeonVar_list[1] as! CastPlaybackState
    let connectedDevice: CastDevice? = nilOrValue(pigeonVar_list[2])
    let currentMedia: MediaInfo? = nilOrValue(pigeonVar_list[3])
    let positionMs: Int64? = nilOrValue(pigeonVar_list[4])
    let durationMs: Int64? = nilOrValue(pigeonVar_list[5])
    let errorMessage: String? = nilOrValue(pigeonVar_list[6])

    return CastSessionState(
      connectionState: connectionState,
      playbackState: playbackState,
      connectedDevice: connectedDevice,
      currentMedia: currentMedia,
      positionMs: positionMs,
      durationMs: durationMs,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      connectionState,
      playbackState,
      connectedDevice,
      currentMedia,
      positionMs,
      durationMs,
      errorMessage,
    ]
  }
  static func == (lhs: CastSessionState, rhs: CastSessionState) -> Bool {
    return deepEqualsCastApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCastApi(value: toList(), hasher: &hasher)
  }
}

private class CastApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CastProvider(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CastConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CastPlaybackState(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MediaType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return CastDevice.fromList(self.readValue() as! [Any?])
    case 134:
      return MediaInfo.fromList(self.readValue() as! [Any?])
    case 135:
      return CastSessionState.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CastApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CastProvider {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CastConnectionState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CastPlaybackState {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? MediaType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? CastDevice {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? MediaInfo {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? CastSessionState {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CastApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CastApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CastApiPigeonCodecWriter(data: data)
  }
}

class CastApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CastApiPigeonCodec(readerWriter: CastApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CastHostApi {
  func startDiscovery() throws
  func stopDiscovery() throws
  func getDiscoveredDevices() throws -> [CastDevice]
  func connect(deviceId: String) throws
  func disconnect() throws
  func loadMedia(mediaInfo: MediaInfo, autoplay: Bool, positionMs: Int64) throws
  func play() throws
  func pause() throws
  func seek(positionMs: Int64) throws
  func stop() throws
  func setVolume(volume: Double) throws
  func setMuted(muted: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CastHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CastApiPigeonCodec.shared }
  /// Sets up an instance of `CastHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CastHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.startDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.startDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDiscoveryChannel.setMessageHandler(nil)
    }
    let stopDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.stopDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.stopDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDiscoveryChannel.setMessageHandler(nil)
    }
    let getDiscoveredDevicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.getDiscoveredDevices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDiscoveredDevicesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDiscoveredDevices()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDiscoveredDevicesChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        do {
          try api.connect(deviceId: deviceIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        do {
          try api.disconnect()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let loadMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.loadMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaInfoArg = args[0] as! MediaInfo
        let autoplayArg = args[1] as! Bool
        let positionMsArg = args[2] as! Int64
        do {
          try api.loadMedia(mediaInfo: mediaInfoArg, autoplay: autoplayArg, positionMs: positionMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadMediaChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { _, reply in
        do {
          try api.play()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let seekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.seek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionMsArg = args[0] as! Int64
        do {
          try api.seek(positionMs: positionMsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      seekChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let volumeArg = args[0] as! Double
        do {
          try api.setVolume(volume: volumeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
    let setMutedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pitcher.CastHostApi.setMuted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMutedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mutedArg = args[0] as! Bool
        do {
          try api.setMuted(muted: mutedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMutedChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CastFlutterApiProtocol {
  func onDevicesChanged(devices devicesArg: [CastDevice], completion: @escaping (Result<Void, CastApiError>) -> Void)
  func onStateChanged(state stateArg: CastSessionState, completion: @escaping (Result<Void, CastApiError>) -> Void)
}
class CastFlutterApi: CastFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CastApiPigeonCodec {
    return CastApiPigeonCodec.shared
  }
  func onDevicesChanged(devices devicesArg: [CastDevice], completion: @escaping (Result<Void, CastApiError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pitcher.CastFlutterApi.onDevicesChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([devicesArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(CastApiError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStateChanged(state stateArg: CastSessionState, completion: @escaping (Result<Void, CastApiError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.pitcher.CastFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(CastApiError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
