// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.rohanjsh.pitcher.cast

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CastApiPigeonUtils {

  fun createConnectionError(channelName: String): CastApiError {
    return CastApiError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is CastApiError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class CastApiError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class CastProvider(val raw: Int) {
  CHROMECAST(0),
  AIRPLAY(1);

  companion object {
    fun ofRaw(raw: Int): CastProvider? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CastConnectionState(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2);

  companion object {
    fun ofRaw(raw: Int): CastConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CastPlaybackState(val raw: Int) {
  IDLE(0),
  LOADING(1),
  PLAYING(2),
  PAUSED(3),
  ENDED(4),
  ERROR(5);

  companion object {
    fun ofRaw(raw: Int): CastPlaybackState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MediaType(val raw: Int) {
  VIDEO(0),
  AUDIO(1);

  companion object {
    fun ofRaw(raw: Int): MediaType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CastDevice (
  val id: String,
  val name: String,
  val provider: CastProvider,
  val modelName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CastDevice {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val provider = pigeonVar_list[2] as CastProvider
      val modelName = pigeonVar_list[3] as String?
      return CastDevice(id, name, provider, modelName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      provider,
      modelName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CastDevice) {
      return false
    }
    if (this === other) {
      return true
    }
    return CastApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaInfo (
  val contentUrl: String,
  val title: String,
  val mediaType: MediaType,
  val subtitle: String? = null,
  val imageUrl: String? = null,
  val contentType: String? = null,
  val duration: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfo {
      val contentUrl = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val mediaType = pigeonVar_list[2] as MediaType
      val subtitle = pigeonVar_list[3] as String?
      val imageUrl = pigeonVar_list[4] as String?
      val contentType = pigeonVar_list[5] as String?
      val duration = pigeonVar_list[6] as Long?
      return MediaInfo(contentUrl, title, mediaType, subtitle, imageUrl, contentType, duration)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentUrl,
      title,
      mediaType,
      subtitle,
      imageUrl,
      contentType,
      duration,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return CastApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CastSessionState (
  val connectionState: CastConnectionState,
  val playbackState: CastPlaybackState,
  val connectedDevice: CastDevice? = null,
  val currentMedia: MediaInfo? = null,
  val positionMs: Long? = null,
  val durationMs: Long? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CastSessionState {
      val connectionState = pigeonVar_list[0] as CastConnectionState
      val playbackState = pigeonVar_list[1] as CastPlaybackState
      val connectedDevice = pigeonVar_list[2] as CastDevice?
      val currentMedia = pigeonVar_list[3] as MediaInfo?
      val positionMs = pigeonVar_list[4] as Long?
      val durationMs = pigeonVar_list[5] as Long?
      val errorMessage = pigeonVar_list[6] as String?
      return CastSessionState(connectionState, playbackState, connectedDevice, currentMedia, positionMs, durationMs, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      connectionState,
      playbackState,
      connectedDevice,
      currentMedia,
      positionMs,
      durationMs,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CastSessionState) {
      return false
    }
    if (this === other) {
      return true
    }
    return CastApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CastApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CastProvider.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CastConnectionState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CastPlaybackState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaType.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CastDevice.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfo.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CastSessionState.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CastProvider -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CastConnectionState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is CastPlaybackState -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is MediaType -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is CastDevice -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MediaInfo -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CastSessionState -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CastHostApi {
  fun startDiscovery()
  fun stopDiscovery()
  fun getDiscoveredDevices(): List<CastDevice>
  fun connect(deviceId: String)
  fun disconnect()
  fun showAirPlayPicker()
  fun loadMedia(mediaInfo: MediaInfo, autoplay: Boolean, positionMs: Long)
  fun play()
  fun pause()
  fun seek(positionMs: Long)
  fun stop()
  fun setVolume(volume: Double)
  fun setMuted(muted: Boolean)

  companion object {
    /** The codec used by CastHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastApiPigeonCodec()
    }
    /** Sets up an instance of `CastHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CastHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.startDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.stopDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.getDiscoveredDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDiscoveredDevices())
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.connect(deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disconnect()
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.showAirPlayPicker$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.showAirPlayPicker()
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.loadMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mediaInfoArg = args[0] as MediaInfo
            val autoplayArg = args[1] as Boolean
            val positionMsArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.loadMedia(mediaInfoArg, autoplayArg, positionMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.play()
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.seek$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val positionMsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.seek(positionMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.setVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val volumeArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setVolume(volumeArg)
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pitcher.CastHostApi.setMuted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mutedArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setMuted(mutedArg)
              listOf(null)
            } catch (exception: Throwable) {
              CastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CastFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CastFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CastApiPigeonCodec()
    }
  }
  fun onDevicesChanged(devicesArg: List<CastDevice>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.pitcher.CastFlutterApi.onDevicesChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(devicesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(CastApiError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CastApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onStateChanged(stateArg: CastSessionState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.pitcher.CastFlutterApi.onStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(CastApiError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CastApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
